# Generated by Django 3.1.6 on 2021-02-04 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='articles',
            fields=[
                ('id', models.PositiveIntegerField(default=0, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=200)),
                ('title', models.TextField(blank=True)),
                ('lead', models.TextField(blank=True)),
                ('author', models.CharField(max_length=100)),
                ('publishdate', models.CharField(max_length=100)),
                ('text', models.TextField(blank=True)),
                ('language', models.CharField(max_length=100)),
                ('image_url', models.TextField(blank=True)),
            ],
        ),
    ]
