# Generated by Django 3.1.6 on 2021-02-08 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='articles',
            new_name='Article',
        ),
    ]
