# Generated by Django 3.1.6 on 2021-02-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20210208_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='BerlinerZeitung',
            fields=[
                ('id', models.PositiveIntegerField(default=0, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=200)),
                ('title', models.TextField(blank=True)),
                ('author', models.CharField(max_length=200)),
                ('publishdate', models.CharField(max_length=100)),
                ('text', models.TextField(blank=True)),
                ('language', models.CharField(max_length=200)),
                ('image_url', models.CharField(max_length=200)),
            ],
        ),
    ]
